import type { AlumniRegistration } from '../../types'

export const MOCK_ALUMNI: AlumniRegistration[] = [
  {
    id: 'alum-001',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-28T09:15:00Z',
    fullName: 'Yaw Darko',
    gender: 'MALE',
    dateOfBirth: '1985-04-12',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Yaw+Darko&background=001B50&color=FFF8DC&bold=true',
    email: 'yaw.darko@gmail.com',
    mobileNumber: '+233244123456',
    altPhoneNumber: '+233208111222',
    residentialAddress: '14 Airport Residential, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2003,
    programme: 'SCIENCE',
    house: 'ACKAH',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Software Engineer',
    organization: 'Hubtel Ghana',
    areaOfExpertise: ['Technology', 'Software Development'],
    emergencyContactNumber: '+233244999888',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Akua Darko',
    nextOfKinContact: '+233244999888',
    nextOfKinRelationship: 'Spouse',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Technology', 'Mentorship'],
    isAvailableAsMentor: true,
    mentorBio: 'Experienced software engineer with 10+ years in the tech industry. Happy to mentor young graduates.',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-28T09:15:00Z',
    updatedAt: '2024-10-28T09:15:00Z',
  },
  {
    id: 'alum-002',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-10-15T11:30:00Z',
    reviewedAt: '2024-10-16T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Efua Asante',
    gender: 'FEMALE',
    dateOfBirth: '1990-07-22',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Efua+Asante&background=001B50&color=FFF8DC&bold=true',
    email: 'efua.asante@yahoo.com',
    mobileNumber: '+233208765432',
    altPhoneNumber: '+233244332211',
    residentialAddress: '7 Cantonments Road, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2008,
    programme: 'BUSINESS',
    house: 'DENSU',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Business Owner',
    organization: 'Efua Fashions Ltd',
    areaOfExpertise: ['Fashion', 'Design', 'Entrepreneurship'],
    emergencyContactNumber: '+233208111222',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Kofi Asante',
    nextOfKinContact: '+233208111222',
    nextOfKinRelationship: 'Father',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Business', 'Fashion'],
    isAvailableAsMentor: true,
    mentorBio: 'Fashion entrepreneur passionate about helping young women start their own businesses.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-10-16T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-10-15T11:30:00Z',
    updatedAt: '2024-10-16T09:00:00Z',
  },
  {
    id: 'alum-003',
    status: 'rejected',
    membershipStatus: 'INACTIVE',
    submittedAt: '2024-10-10T14:20:00Z',
    reviewedAt: '2024-10-11T10:00:00Z',
    reviewedBy: 'user-003',
    rejectionReason: 'Incomplete information provided. Missing emergency contact details.',
    fullName: 'Kweku Mensah',
    gender: 'MALE',
    dateOfBirth: '1995-11-05',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Kweku+Mensah&background=001B50&color=FFF8DC&bold=true',
    email: 'kweku.mensah@hotmail.com',
    mobileNumber: '+233277345678',
    altPhoneNumber: '',
    residentialAddress: '22 Legon Road, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2013,
    programme: 'GENERAL_ARTS',
    house: 'TANO',
    employmentType: 'STUDENT',
    occupation: 'Graduate Student',
    organization: 'University of Ghana',
    areaOfExpertise: ['Research', 'Social Sciences'],
    emergencyContactNumber: '',
    emergencyRelationship: '',
    nextOfKinName: 'Adwoa Mensah',
    nextOfKinContact: '+233277111000',
    nextOfKinRelationship: 'Mother',
    isWhatsAppMember: false,
    willingToVolunteer: 'MAYBE',
    preferredContributions: [],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-10T14:20:00Z',
    updatedAt: '2024-10-11T10:00:00Z',
  },
  {
    id: 'alum-004',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-29T16:45:00Z',
    fullName: 'Akosua Boateng',
    gender: 'FEMALE',
    dateOfBirth: '1988-03-18',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Akosua+Boateng&background=001B50&color=FFF8DC&bold=true',
    email: 'akosua.boateng@gmail.com',
    mobileNumber: '+233244567890',
    altPhoneNumber: '+233208445566',
    residentialAddress: '5 Ring Road Central, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2006,
    programme: 'HOME_ECONOMICS',
    house: 'NKRUMAH',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Nurse',
    organization: 'Korle-Bu Teaching Hospital',
    areaOfExpertise: ['Healthcare', 'Nursing'],
    emergencyContactNumber: '+233244777666',
    emergencyRelationship: 'Husband',
    nextOfKinName: 'Joseph Boateng',
    nextOfKinContact: '+233244777666',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Healthcare', 'Community Service'],
    isAvailableAsMentor: true,
    mentorBio: 'Registered nurse with extensive experience at Korle-Bu. Willing to guide nursing students.',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-29T16:45:00Z',
    updatedAt: '2024-10-29T16:45:00Z',
  },
  {
    id: 'alum-005',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-09-20T08:00:00Z',
    reviewedAt: '2024-09-21T09:30:00Z',
    reviewedBy: 'user-003',
    fullName: 'Kwabena Agyei',
    gender: 'MALE',
    dateOfBirth: '1982-09-30',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Kwabena+Agyei&background=001B50&color=FFF8DC&bold=true',
    email: 'kwabena.agyei@outlook.com',
    mobileNumber: '+233208234567',
    altPhoneNumber: '+233244876543',
    residentialAddress: '3 East Legon, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2000,
    programme: 'SCIENCE',
    house: 'PRA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Medical Doctor',
    organization: 'Ridge Hospital',
    areaOfExpertise: ['Medicine', 'Surgery'],
    emergencyContactNumber: '+233208999000',
    emergencyRelationship: 'Wife',
    nextOfKinName: 'Ama Agyei',
    nextOfKinContact: '+233208999000',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Healthcare', 'Science'],
    isAvailableAsMentor: true,
    mentorBio: 'Consultant surgeon at Ridge Hospital. Open to mentoring aspiring medical students.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-09-21T09:30:00Z',
    consentGiven: true,
    createdAt: '2024-09-20T08:00:00Z',
    updatedAt: '2024-09-21T09:30:00Z',
  },
  {
    id: 'alum-006',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-30T10:00:00Z',
    fullName: 'Esi Quaye',
    gender: 'FEMALE',
    dateOfBirth: '1997-06-14',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Esi+Quaye&background=001B50&color=FFF8DC&bold=true',
    email: 'esi.quaye@gmail.com',
    mobileNumber: '+233554321098',
    altPhoneNumber: '',
    residentialAddress: '88 Dzorwulu, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2015,
    programme: 'VISUAL_ARTS',
    house: 'VOLTA',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Graphic Designer',
    organization: 'Freelance',
    areaOfExpertise: ['Arts', 'Graphic Design'],
    emergencyContactNumber: '+233554111222',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Kwesi Quaye',
    nextOfKinContact: '+233554111222',
    nextOfKinRelationship: 'Father',
    isWhatsAppMember: true,
    willingToVolunteer: 'NO',
    preferredContributions: ['Arts'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-30T10:00:00Z',
    updatedAt: '2024-10-30T10:00:00Z',
  },
  {
    id: 'alum-007',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-09-05T13:00:00Z',
    reviewedAt: '2024-09-06T11:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Nana Osei',
    gender: 'MALE',
    dateOfBirth: '1975-12-01',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Nana+Osei&background=001B50&color=FFF8DC&bold=true',
    email: 'nana.osei@gmail.com',
    mobileNumber: '+233244876543',
    altPhoneNumber: '+233208334455',
    residentialAddress: '1 Independence Ave, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 1993,
    programme: 'BUSINESS',
    house: 'ACKAH',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Entrepreneur',
    organization: 'Osei Holdings',
    areaOfExpertise: ['Business', 'Finance', 'Leadership'],
    emergencyContactNumber: '+233244333444',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Abena Osei',
    nextOfKinContact: '+233244333444',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Business', 'Finance', 'Mentorship'],
    isAvailableAsMentor: true,
    mentorBio: 'Serial entrepreneur with businesses across West Africa. Passionate about empowering the next generation.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-09-06T11:00:00Z',
    consentGiven: true,
    createdAt: '2024-09-05T13:00:00Z',
    updatedAt: '2024-09-06T11:00:00Z',
  },
  {
    id: 'alum-008',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-31T07:30:00Z',
    fullName: 'Adwoa Frimpong',
    gender: 'FEMALE',
    dateOfBirth: '1993-08-27',
    maritalStatus: 'DIVORCED',
    photoUrl: 'https://ui-avatars.com/api/?name=Adwoa+Frimpong&background=001B50&color=FFF8DC&bold=true',
    email: 'adwoa.frimpong@gmail.com',
    mobileNumber: '+233277654321',
    altPhoneNumber: '+233244998877',
    residentialAddress: '12 Osu Oxford Street, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2011,
    programme: 'GENERAL_ARTS',
    house: 'DENSU',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Teacher',
    organization: 'GES - Accra',
    areaOfExpertise: ['Education', 'English Language'],
    emergencyContactNumber: '+233277222333',
    emergencyRelationship: 'Sibling',
    nextOfKinName: 'Kofi Frimpong',
    nextOfKinContact: '+233277222333',
    nextOfKinRelationship: 'Brother',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Education', 'Community Service'],
    isAvailableAsMentor: true,
    mentorBio: 'Experienced teacher with a passion for literacy programs.',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-31T07:30:00Z',
    updatedAt: '2024-10-31T07:30:00Z',
  },
  {
    id: 'alum-009',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-08-15T09:00:00Z',
    reviewedAt: '2024-08-16T10:00:00Z',
    reviewedBy: 'user-001',
    fullName: 'Samuel Tetteh',
    gender: 'MALE',
    dateOfBirth: '1979-02-14',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Samuel+Tetteh&background=001B50&color=FFF8DC&bold=true',
    email: 'samuel.tetteh@gmail.com',
    mobileNumber: '+233244098765',
    altPhoneNumber: '+233208567890',
    residentialAddress: '45 Adabraka, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 1997,
    programme: 'SCIENCE',
    house: 'TANO',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Civil Engineer',
    organization: 'Ghana Highways Authority',
    areaOfExpertise: ['Engineering', 'Infrastructure'],
    emergencyContactNumber: '+233244555666',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Grace Tetteh',
    nextOfKinContact: '+233244555666',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: false,
    willingToVolunteer: 'NO',
    preferredContributions: [],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-08-16T10:00:00Z',
    consentGiven: true,
    createdAt: '2024-08-15T09:00:00Z',
    updatedAt: '2024-08-16T10:00:00Z',
  },
  {
    id: 'alum-010',
    status: 'rejected',
    membershipStatus: 'INACTIVE',
    submittedAt: '2024-10-05T15:00:00Z',
    reviewedAt: '2024-10-06T09:00:00Z',
    reviewedBy: 'user-003',
    rejectionReason: 'Year group not matching school records. Please verify and resubmit.',
    fullName: 'Bernardine Antwi',
    gender: 'FEMALE',
    dateOfBirth: '1991-05-19',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Bernardine+Antwi&background=001B50&color=FFF8DC&bold=true',
    email: 'bernardine.antwi@gmail.com',
    mobileNumber: '+233554876543',
    altPhoneNumber: '+233244776655',
    residentialAddress: '34 North Labone, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2010,
    programme: 'HOME_ECONOMICS',
    house: 'NKRUMAH',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Nutritionist',
    organization: 'Nutrition Foundation Ghana',
    areaOfExpertise: ['Nutrition', 'Health'],
    emergencyContactNumber: '+233554333222',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Emmanuel Antwi',
    nextOfKinContact: '+233554333222',
    nextOfKinRelationship: 'Father',
    isWhatsAppMember: true,
    willingToVolunteer: 'MAYBE',
    preferredContributions: ['Health'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-05T15:00:00Z',
    updatedAt: '2024-10-06T09:00:00Z',
  },
  {
    id: 'alum-011',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-27T12:00:00Z',
    fullName: 'Owusu Barimah',
    gender: 'MALE',
    dateOfBirth: '1987-10-10',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Owusu+Barimah&background=001B50&color=FFF8DC&bold=true',
    email: 'owusu.barimah@gmail.com',
    mobileNumber: '+233208543210',
    altPhoneNumber: '+447700998877',
    residentialAddress: '15 Oxford Street, London',
    city: 'London',
    country: 'United Kingdom',
    yearGroup: 2005,
    programme: 'BUSINESS',
    house: 'PRA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Banker',
    organization: 'Barclays Bank UK',
    areaOfExpertise: ['Finance', 'Banking'],
    emergencyContactNumber: '+447700123456',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Serena Barimah',
    nextOfKinContact: '+447700123456',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Finance', 'International Relations'],
    isAvailableAsMentor: true,
    mentorBio: 'Banking professional based in London. Can help with career guidance in finance.',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-27T12:00:00Z',
    updatedAt: '2024-10-27T12:00:00Z',
  },
  {
    id: 'alum-012',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-07-10T10:00:00Z',
    reviewedAt: '2024-07-11T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Comfort Acheampong',
    gender: 'FEMALE',
    dateOfBirth: '1985-01-25',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Comfort+Acheampong&background=001B50&color=FFF8DC&bold=true',
    email: 'comfort.acheampong@gmail.com',
    mobileNumber: '+14155552671',
    altPhoneNumber: '+14155553344',
    residentialAddress: '456 Market St, San Francisco, CA',
    city: 'San Francisco',
    country: 'United States',
    yearGroup: 2003,
    programme: 'SCIENCE',
    house: 'VOLTA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Pharmacist',
    organization: 'UCSF Medical Center',
    areaOfExpertise: ['Pharmacy', 'Medicine'],
    emergencyContactNumber: '+14155559876',
    emergencyRelationship: 'Husband',
    nextOfKinName: 'Daniel Acheampong',
    nextOfKinContact: '+14155559876',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Healthcare', 'Science', 'Scholarship'],
    isAvailableAsMentor: true,
    mentorBio: 'Pharmacist in the Bay Area. Happy to support scholarship initiatives for UPOSA students.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-07-11T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-07-10T10:00:00Z',
    updatedAt: '2024-07-11T09:00:00Z',
  },
  {
    id: 'alum-013',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-26T08:45:00Z',
    fullName: 'Fiifi Koomson',
    gender: 'MALE',
    dateOfBirth: '1999-03-07',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Fiifi+Koomson&background=001B50&color=FFF8DC&bold=true',
    email: 'fiifi.koomson@gmail.com',
    mobileNumber: '+233553456789',
    altPhoneNumber: '',
    residentialAddress: '15 Asylum Down, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2017,
    programme: 'VISUAL_ARTS',
    house: 'ACKAH',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Photographer',
    organization: 'Fiifi Studios',
    areaOfExpertise: ['Photography', 'Media'],
    emergencyContactNumber: '+233553111000',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Mabel Koomson',
    nextOfKinContact: '+233553111000',
    nextOfKinRelationship: 'Mother',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Arts', 'Media'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-26T08:45:00Z',
    updatedAt: '2024-10-26T08:45:00Z',
  },
  {
    id: 'alum-014',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-06-20T14:00:00Z',
    reviewedAt: '2024-06-21T10:00:00Z',
    reviewedBy: 'user-001',
    fullName: 'Patricia Asiedu',
    gender: 'FEMALE',
    dateOfBirth: '1980-07-04',
    maritalStatus: 'WIDOWED',
    photoUrl: 'https://ui-avatars.com/api/?name=Patricia+Asiedu&background=001B50&color=FFF8DC&bold=true',
    email: 'patricia.asiedu@gmail.com',
    mobileNumber: '+233244210987',
    altPhoneNumber: '+233208112244',
    residentialAddress: '9 Roman Ridge, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 1998,
    programme: 'GENERAL_ARTS',
    house: 'NKRUMAH',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Lawyer',
    organization: 'Attorney General Dept',
    areaOfExpertise: ['Law', 'Governance'],
    emergencyContactNumber: '+233244888999',
    emergencyRelationship: 'Sibling',
    nextOfKinName: 'Joseph Asiedu',
    nextOfKinContact: '+233244888999',
    nextOfKinRelationship: 'Brother',
    isWhatsAppMember: false,
    willingToVolunteer: 'YES',
    preferredContributions: ['Law', 'Advocacy'],
    isAvailableAsMentor: true,
    mentorBio: 'State attorney with 20+ years of legal experience. Available for career guidance in law.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-06-21T10:00:00Z',
    consentGiven: true,
    createdAt: '2024-06-20T14:00:00Z',
    updatedAt: '2024-06-21T10:00:00Z',
  },
  {
    id: 'alum-015',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-10-31T17:00:00Z',
    fullName: 'Richard Oppong',
    gender: 'MALE',
    dateOfBirth: '1992-11-30',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Richard+Oppong&background=001B50&color=FFF8DC&bold=true',
    email: 'richard.oppong@gmail.com',
    mobileNumber: '+233207654321',
    altPhoneNumber: '',
    residentialAddress: '33 Haatso, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2010,
    programme: 'SCIENCE',
    house: 'DENSU',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'IT Specialist',
    organization: 'MTN Ghana',
    areaOfExpertise: ['Technology', 'Telecommunications'],
    emergencyContactNumber: '+233207111222',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Victoria Oppong',
    nextOfKinContact: '+233207111222',
    nextOfKinRelationship: 'Mother',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Technology', 'Innovation'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-10-31T17:00:00Z',
    updatedAt: '2024-10-31T17:00:00Z',
  },
  {
    id: 'alum-016',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-05-10T09:00:00Z',
    reviewedAt: '2024-05-11T08:00:00Z',
    reviewedBy: 'user-001',
    fullName: 'Emmanuel Adjei-Mensah',
    gender: 'MALE',
    dateOfBirth: '1983-06-20',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Emmanuel+Adjei&background=001B50&color=FFF8DC&bold=true',
    email: 'emmanuel.adjei@gmail.com',
    mobileNumber: '+233244332211',
    altPhoneNumber: '+233208556677',
    residentialAddress: '22 Ahodwo, Kumasi',
    city: 'Kumasi',
    country: 'Ghana',
    yearGroup: 2001,
    programme: 'SCIENCE',
    house: 'TANO',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Dentist',
    organization: 'Adjei Dental Clinic',
    areaOfExpertise: ['Dentistry', 'Healthcare'],
    emergencyContactNumber: '+233244998877',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Florence Adjei-Mensah',
    nextOfKinContact: '+233244998877',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Healthcare', 'Community Service'],
    isAvailableAsMentor: true,
    mentorBio: 'Running a dental practice in Kumasi for over 10 years. Happy to mentor health professionals.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-05-11T08:00:00Z',
    consentGiven: true,
    createdAt: '2024-05-10T09:00:00Z',
    updatedAt: '2024-05-11T08:00:00Z',
  },
  {
    id: 'alum-017',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-11-01T06:00:00Z',
    fullName: 'Abigail Osei-Tutu',
    gender: 'FEMALE',
    dateOfBirth: '1996-02-28',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Abigail+Osei&background=001B50&color=FFF8DC&bold=true',
    email: 'abigail.oseitutu@gmail.com',
    mobileNumber: '+233554009988',
    altPhoneNumber: '',
    residentialAddress: '10 Spintex Road, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2014,
    programme: 'BUSINESS',
    house: 'VOLTA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Marketing Manager',
    organization: 'Fan Milk Ghana',
    areaOfExpertise: ['Marketing', 'Brand Management'],
    emergencyContactNumber: '+233554112233',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Nana Osei-Tutu',
    nextOfKinContact: '+233554112233',
    nextOfKinRelationship: 'Father',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Marketing', 'Business'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-11-01T06:00:00Z',
    updatedAt: '2024-11-01T06:00:00Z',
  },
  {
    id: 'alum-018',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-04-20T11:00:00Z',
    reviewedAt: '2024-04-21T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Isaac Danquah',
    gender: 'MALE',
    dateOfBirth: '1978-08-15',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Isaac+Danquah&background=001B50&color=FFF8DC&bold=true',
    email: 'isaac.danquah@outlook.com',
    mobileNumber: '+233208776655',
    altPhoneNumber: '+233244887766',
    residentialAddress: '5 Ridge, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 1996,
    programme: 'GENERAL_ARTS',
    house: 'PRA',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Diplomat',
    organization: 'Ministry of Foreign Affairs',
    areaOfExpertise: ['International Relations', 'Diplomacy'],
    emergencyContactNumber: '+233208665544',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Mercy Danquah',
    nextOfKinContact: '+233208665544',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'NO',
    preferredContributions: [],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-04-21T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-04-20T11:00:00Z',
    updatedAt: '2024-04-21T09:00:00Z',
  },
  {
    id: 'alum-019',
    status: 'rejected',
    membershipStatus: 'INACTIVE',
    submittedAt: '2024-09-15T16:00:00Z',
    reviewedAt: '2024-09-16T10:00:00Z',
    reviewedBy: 'user-001',
    rejectionReason: 'Duplicate registration detected. Member already registered under a different email.',
    fullName: 'Kwadwo Amankwah',
    gender: 'MALE',
    dateOfBirth: '1994-01-10',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Kwadwo+Amankwah&background=001B50&color=FFF8DC&bold=true',
    email: 'kwadwo.amankwah@yahoo.com',
    mobileNumber: '+233277889900',
    altPhoneNumber: '+233244556677',
    residentialAddress: '18 North Kaneshie, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2012,
    programme: 'VISUAL_ARTS',
    house: 'ACKAH',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Architect',
    organization: 'Amankwah Design Studio',
    areaOfExpertise: ['Architecture', 'Design'],
    emergencyContactNumber: '+233277001122',
    emergencyRelationship: 'Sibling',
    nextOfKinName: 'Akua Amankwah',
    nextOfKinContact: '+233277001122',
    nextOfKinRelationship: 'Sister',
    isWhatsAppMember: true,
    willingToVolunteer: 'MAYBE',
    preferredContributions: ['Arts'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-09-15T16:00:00Z',
    updatedAt: '2024-09-16T10:00:00Z',
  },
  {
    id: 'alum-020',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-03-12T10:00:00Z',
    reviewedAt: '2024-03-13T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Millicent Amoako',
    gender: 'FEMALE',
    dateOfBirth: '1989-12-03',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Millicent+Amoako&background=001B50&color=FFF8DC&bold=true',
    email: 'millicent.amoako@gmail.com',
    mobileNumber: '+233244556677',
    altPhoneNumber: '+233208998877',
    residentialAddress: '9 Bantama, Kumasi',
    city: 'Kumasi',
    country: 'Ghana',
    yearGroup: 2007,
    programme: 'HOME_ECONOMICS',
    house: 'DENSU',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Hotel Manager',
    organization: 'Golden Tulip Kumasi',
    areaOfExpertise: ['Hospitality', 'Management'],
    emergencyContactNumber: '+233244778899',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Robert Amoako',
    nextOfKinContact: '+233244778899',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Hospitality', 'Events'],
    isAvailableAsMentor: true,
    mentorBio: 'Hotel industry professional. Happy to guide students interested in hospitality management.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-03-13T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-03-12T10:00:00Z',
    updatedAt: '2024-03-13T09:00:00Z',
  },
  {
    id: 'alum-021',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-11-02T08:30:00Z',
    fullName: 'Benjamin Ofori-Atta',
    gender: 'MALE',
    dateOfBirth: '1986-04-25',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Benjamin+Ofori&background=001B50&color=FFF8DC&bold=true',
    email: 'ben.oforiatta@gmail.com',
    mobileNumber: '+233208112233',
    altPhoneNumber: '+233244334455',
    residentialAddress: '77 Labone Estate, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2004,
    programme: 'BUSINESS',
    house: 'TANO',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Investment Analyst',
    organization: 'Ecobank Capital',
    areaOfExpertise: ['Investment Banking', 'Financial Analysis'],
    emergencyContactNumber: '+233208445566',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Linda Ofori-Atta',
    nextOfKinContact: '+233208445566',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Finance', 'Mentorship'],
    isAvailableAsMentor: true,
    mentorBio: 'Investment professional at Ecobank. Keen on financial literacy for young alumni.',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-11-02T08:30:00Z',
    updatedAt: '2024-11-02T08:30:00Z',
  },
  {
    id: 'alum-022',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-06-05T12:00:00Z',
    reviewedAt: '2024-06-06T09:00:00Z',
    reviewedBy: 'user-001',
    fullName: 'Priscilla Donkor',
    gender: 'FEMALE',
    dateOfBirth: '1992-09-17',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Priscilla+Donkor&background=001B50&color=FFF8DC&bold=true',
    email: 'priscilla.donkor@gmail.com',
    mobileNumber: '+233277443322',
    altPhoneNumber: '+233244889900',
    residentialAddress: '30 Takoradi Beach Road, Takoradi',
    city: 'Takoradi',
    country: 'Ghana',
    yearGroup: 2010,
    programme: 'SCIENCE',
    house: 'NKRUMAH',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Petroleum Engineer',
    organization: 'Tullow Oil Ghana',
    areaOfExpertise: ['Oil & Gas', 'Engineering'],
    emergencyContactNumber: '+233277556677',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'James Donkor',
    nextOfKinContact: '+233277556677',
    nextOfKinRelationship: 'Father',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Engineering', 'Science'],
    isAvailableAsMentor: true,
    mentorBio: 'Petroleum engineer in the Western Region. Can mentor students in STEM fields.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-06-06T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-06-05T12:00:00Z',
    updatedAt: '2024-06-06T09:00:00Z',
  },
  {
    id: 'alum-023',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-11-03T14:00:00Z',
    fullName: 'Augustine Mensah-Bonsu',
    gender: 'MALE',
    dateOfBirth: '2000-07-09',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Augustine+Mensah&background=001B50&color=FFF8DC&bold=true',
    email: 'augustine.mb@gmail.com',
    mobileNumber: '+233553334455',
    altPhoneNumber: '',
    residentialAddress: '12 Sakumono, Tema',
    city: 'Tema',
    country: 'Ghana',
    yearGroup: 2018,
    programme: 'GENERAL_ARTS',
    house: 'VOLTA',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Content Creator',
    organization: 'Self-Employed',
    areaOfExpertise: ['Digital Media', 'Content Production'],
    emergencyContactNumber: '+233553667788',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Grace Mensah-Bonsu',
    nextOfKinContact: '+233553667788',
    nextOfKinRelationship: 'Mother',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Media', 'Technology'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-11-03T14:00:00Z',
    updatedAt: '2024-11-03T14:00:00Z',
  },
  {
    id: 'alum-024',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-02-18T10:00:00Z',
    reviewedAt: '2024-02-19T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Josephine Appiah',
    gender: 'FEMALE',
    dateOfBirth: '1981-11-22',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Josephine+Appiah&background=001B50&color=FFF8DC&bold=true',
    email: 'josephine.appiah@outlook.com',
    mobileNumber: '+12125551234',
    altPhoneNumber: '+12125556789',
    residentialAddress: '210 West 78th St, New York, NY',
    city: 'New York',
    country: 'United States',
    yearGroup: 1999,
    programme: 'SCIENCE',
    house: 'PRA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Biomedical Researcher',
    organization: 'Columbia University Medical Center',
    areaOfExpertise: ['Biomedical Research', 'Genetics'],
    emergencyContactNumber: '+12125559876',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Michael Appiah',
    nextOfKinContact: '+12125559876',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Science', 'Healthcare', 'Scholarship'],
    isAvailableAsMentor: true,
    mentorBio: 'Biomedical researcher at Columbia. Focused on supporting STEM education in Ghana.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-02-19T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-02-19T09:00:00Z',
  },
  {
    id: 'alum-025',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-11-04T09:00:00Z',
    fullName: 'Daniel Asamoah',
    gender: 'MALE',
    dateOfBirth: '1990-05-14',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Daniel+Asamoah&background=001B50&color=FFF8DC&bold=true',
    email: 'daniel.asamoah@gmail.com',
    mobileNumber: '+233244667788',
    altPhoneNumber: '+233208776655',
    residentialAddress: '6 Asafo Market Area, Kumasi',
    city: 'Kumasi',
    country: 'Ghana',
    yearGroup: 2008,
    programme: 'BUSINESS',
    house: 'ACKAH',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Logistics CEO',
    organization: 'Asamoah Express Ltd',
    areaOfExpertise: ['Supply Chain', 'Logistics'],
    emergencyContactNumber: '+233244990011',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Akosua Asamoah',
    nextOfKinContact: '+233244990011',
    nextOfKinRelationship: 'Wife',
    isWhatsAppMember: true,
    willingToVolunteer: 'NO',
    preferredContributions: [],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-11-04T09:00:00Z',
    updatedAt: '2024-11-04T09:00:00Z',
  },
  {
    id: 'alum-026',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-01-15T10:00:00Z',
    reviewedAt: '2024-01-16T09:00:00Z',
    reviewedBy: 'user-001',
    fullName: 'Felicia Owusu-Ansah',
    gender: 'FEMALE',
    dateOfBirth: '1984-03-30',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Felicia+Owusu&background=001B50&color=FFF8DC&bold=true',
    email: 'felicia.owusuansah@nhs.uk',
    mobileNumber: '+447700445566',
    altPhoneNumber: '+447700112233',
    residentialAddress: '15 Cambridge Road, London',
    city: 'London',
    country: 'United Kingdom',
    yearGroup: 2002,
    programme: 'SCIENCE',
    house: 'DENSU',
    employmentType: 'GOVERNMENT_WORKER',
    occupation: 'Consultant Physician',
    organization: 'NHS - Royal London Hospital',
    areaOfExpertise: ['Medicine', 'Public Health'],
    emergencyContactNumber: '+447700112233',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Kwadwo Owusu-Ansah',
    nextOfKinContact: '+447700112233',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Healthcare', 'Mentorship'],
    isAvailableAsMentor: true,
    mentorBio: 'NHS consultant physician. Available to mentor aspiring medical professionals.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-01-16T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-16T09:00:00Z',
  },
  {
    id: 'alum-027',
    status: 'pending',
    membershipStatus: 'PENDING',
    submittedAt: '2024-11-05T11:00:00Z',
    fullName: 'Kwasi Afrifa',
    gender: 'MALE',
    dateOfBirth: '1998-10-08',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Kwasi+Afrifa&background=001B50&color=FFF8DC&bold=true',
    email: 'kwasi.afrifa@gmail.com',
    mobileNumber: '+233554223344',
    altPhoneNumber: '',
    residentialAddress: '40 Pokuase, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2016,
    programme: 'VISUAL_ARTS',
    house: 'TANO',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'UI/UX Designer',
    organization: 'Freelance',
    areaOfExpertise: ['Design', 'Technology', 'UI/UX'],
    emergencyContactNumber: '+233554556677',
    emergencyRelationship: 'Parent',
    nextOfKinName: 'Elizabeth Afrifa',
    nextOfKinContact: '+233554556677',
    nextOfKinRelationship: 'Mother',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Arts', 'Technology'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-11-05T11:00:00Z',
    updatedAt: '2024-11-05T11:00:00Z',
  },
  {
    id: 'alum-028',
    status: 'approved',
    membershipStatus: 'SUSPENDED',
    submittedAt: '2024-04-05T08:00:00Z',
    reviewedAt: '2024-04-06T09:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Margaret Adu-Gyamfi',
    gender: 'FEMALE',
    dateOfBirth: '1977-08-01',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Margaret+Adu&background=001B50&color=FFF8DC&bold=true',
    email: 'margaret.agyamfi@gmail.com',
    mobileNumber: '+233244112200',
    altPhoneNumber: '+233208334455',
    residentialAddress: '7 Tantra Hill, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 1995,
    programme: 'HOME_ECONOMICS',
    house: 'NKRUMAH',
    employmentType: 'SELF_EMPLOYED',
    occupation: 'Catering Business Owner',
    organization: 'Margies Kitchen Ltd',
    areaOfExpertise: ['Hospitality', 'Catering'],
    emergencyContactNumber: '+233244334455',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Frank Adu-Gyamfi',
    nextOfKinContact: '+233244334455',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Hospitality', 'Events'],
    isAvailableAsMentor: true,
    mentorBio: 'Running a catering business for 15+ years. Passionate about training young caterers.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-04-06T09:00:00Z',
    consentGiven: true,
    createdAt: '2024-04-05T08:00:00Z',
    updatedAt: '2025-01-10T14:00:00Z',
  },
  {
    id: 'alum-029',
    status: 'rejected',
    membershipStatus: 'INACTIVE',
    submittedAt: '2024-08-20T15:00:00Z',
    reviewedAt: '2024-08-21T10:00:00Z',
    reviewedBy: 'user-001',
    rejectionReason: 'Cannot verify school attendance records. Please provide additional proof of enrollment.',
    fullName: 'Collins Badu',
    gender: 'MALE',
    dateOfBirth: '1993-12-25',
    maritalStatus: 'SINGLE',
    photoUrl: 'https://ui-avatars.com/api/?name=Collins+Badu&background=001B50&color=FFF8DC&bold=true',
    email: 'collins.badu@gmail.com',
    mobileNumber: '+233277990011',
    altPhoneNumber: '+233244667788',
    residentialAddress: '55 Dome, Accra',
    city: 'Accra',
    country: 'Ghana',
    yearGroup: 2011,
    programme: 'GENERAL_ARTS',
    house: 'PRA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Journalist',
    organization: 'Multimedia Group Ltd',
    areaOfExpertise: ['Journalism', 'Media'],
    emergencyContactNumber: '+233277112233',
    emergencyRelationship: 'Sibling',
    nextOfKinName: 'Sandra Badu',
    nextOfKinContact: '+233277112233',
    nextOfKinRelationship: 'Sister',
    isWhatsAppMember: true,
    willingToVolunteer: 'MAYBE',
    preferredContributions: ['Media'],
    isAvailableAsMentor: false,
    mentorBio: '',
    isVerified: false,
    isApproved: false,
    approvedAt: '',
    consentGiven: true,
    createdAt: '2024-08-20T15:00:00Z',
    updatedAt: '2024-08-21T10:00:00Z',
  },
  {
    id: 'alum-030',
    status: 'approved',
    membershipStatus: 'ACTIVE',
    submittedAt: '2024-03-01T09:00:00Z',
    reviewedAt: '2024-03-02T08:00:00Z',
    reviewedBy: 'user-003',
    fullName: 'Gifty Mensah-Sarpong',
    gender: 'FEMALE',
    dateOfBirth: '1988-07-12',
    maritalStatus: 'MARRIED',
    photoUrl: 'https://ui-avatars.com/api/?name=Gifty+Mensah&background=001B50&color=FFF8DC&bold=true',
    email: 'gifty.sarpong@gmail.com',
    mobileNumber: '+49171234567',
    altPhoneNumber: '+49171876543',
    residentialAddress: '25 Berliner Strasse, Berlin',
    city: 'Berlin',
    country: 'Germany',
    yearGroup: 2006,
    programme: 'BUSINESS',
    house: 'VOLTA',
    employmentType: 'PRIVATE_WORKER',
    occupation: 'Supply Chain Manager',
    organization: 'Siemens AG',
    areaOfExpertise: ['Supply Chain Management', 'Operations'],
    emergencyContactNumber: '+49171876543',
    emergencyRelationship: 'Spouse',
    nextOfKinName: 'Hans Sarpong',
    nextOfKinContact: '+49171876543',
    nextOfKinRelationship: 'Husband',
    isWhatsAppMember: true,
    willingToVolunteer: 'YES',
    preferredContributions: ['Business', 'International Relations'],
    isAvailableAsMentor: true,
    mentorBio: 'Supply chain professional at Siemens. Can mentor alumni interested in working in Europe.',
    isVerified: true,
    isApproved: true,
    approvedAt: '2024-03-02T08:00:00Z',
    consentGiven: true,
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-03-02T08:00:00Z',
  },
]
