import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Job } from '../types'

const MOCK_JOBS: Job[] = [
  { id: 'job-1', title: 'Software Engineer (Full Stack)', company: 'Hubtel Ghana', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Hubtel is looking for a talented full stack engineer to join our growing team. You will work on our flagship mobile commerce platform used by millions of Ghanaians.', contactEmail: 'careers@hubtel.com', externalUrl: 'https://hubtel.com/careers/software-engineer', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-04-30T23:59:00.000Z', applications: [], createdAt: '2026-03-01T08:00:00.000Z', updatedAt: '2026-03-01T08:00:00.000Z' },
  { id: 'job-2', title: 'Finance Analyst', company: 'Stanbic Bank Ghana', location: 'Kumasi, Ghana', jobType: 'FULL_TIME', description: 'Stanbic Bank is seeking a finance analyst to support our retail banking operations in the Ashanti region. The role involves financial modelling, reporting, and portfolio analysis.', contactEmail: 'hr@stanbicbank.com.gh', externalUrl: 'https://stanbicbank.com.gh/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-04-15T23:59:00.000Z', applications: [], createdAt: '2026-02-20T08:00:00.000Z', updatedAt: '2026-02-20T08:00:00.000Z' },
  { id: 'job-3', title: 'Graduate Internship - Marketing', company: 'Unilever Ghana', location: 'Accra, Ghana', jobType: 'INTERNSHIP', description: 'Unilever Ghana is offering a 6-month graduate internship in the Marketing department. Interns will gain hands-on experience in brand management, consumer research, and campaign execution.', contactEmail: 'internships@unilever.com', externalUrl: 'https://unilever.com/careers/internship-ghana', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-03-31T23:59:00.000Z', applications: [], createdAt: '2026-02-25T08:00:00.000Z', updatedAt: '2026-02-25T08:00:00.000Z' },
  { id: 'job-4', title: 'Volunteer Teacher - STEM Programme', company: 'UPOSA Foundation', location: 'Kumasi, Ghana (Opoku Ware School)', jobType: 'VOLUNTEER', description: 'UPOSA Foundation is recruiting volunteer teachers for our STEM mentorship programme at Opoku Ware School. Volunteers will spend weekends teaching and mentoring Form 1 and Form 2 students.', contactEmail: 'volunteer@uposa.org', externalUrl: 'https://uposa.org/volunteer', postedByName: 'Abena Mensah-Kusi', isApproved: true, expiresAt: '2026-05-01T23:59:00.000Z', applications: [], createdAt: '2026-03-05T08:00:00.000Z', updatedAt: '2026-03-05T08:00:00.000Z' },
  { id: 'job-5', title: 'Data Analyst', company: 'MTN Ghana', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'MTN Ghana seeks a data analyst to support business intelligence and reporting across commercial operations. You will transform data into actionable insights for decision-makers.', contactEmail: 'careers@mtn.com.gh', externalUrl: 'https://mtn.com.gh/careers/data-analyst', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-04-20T23:59:00.000Z', applications: [], createdAt: '2026-03-08T08:00:00.000Z', updatedAt: '2026-03-08T08:00:00.000Z' },
  { id: 'job-6', title: 'Project Manager - Construction', company: 'Asamoah Express Ltd', location: 'Kumasi, Ghana', jobType: 'FULL_TIME', description: 'Asamoah Express is looking for a project manager to oversee logistics infrastructure projects across the Ashanti region. You will manage timelines, budgets, and contractor relationships.', contactEmail: 'careers@asamoahexpress.com', externalUrl: 'https://asamoahexpress.com/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-05-15T23:59:00.000Z', applications: [], createdAt: '2026-03-10T08:00:00.000Z', updatedAt: '2026-03-10T08:00:00.000Z' },
  { id: 'job-7', title: 'Registered Nurse', company: 'Korle-Bu Teaching Hospital', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Korle-Bu is recruiting registered nurses for the paediatric ward. Competitive salary and professional development opportunities available.', contactEmail: 'hr@kbth.gov.gh', externalUrl: 'https://kbth.gov.gh/careers', postedByName: 'Abena Mensah-Kusi', isApproved: true, expiresAt: '2026-04-10T23:59:00.000Z', applications: [], createdAt: '2026-02-15T08:00:00.000Z', updatedAt: '2026-02-15T08:00:00.000Z' },
  { id: 'job-8', title: 'Legal Associate', company: 'Asante & Co. Law Firm', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Asante & Co. is hiring a legal associate to join our corporate law practice. You will handle contract drafting, due diligence, and regulatory compliance matters.', contactEmail: 'careers@asantelaw.com', externalUrl: 'https://asantelaw.com/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-04-25T23:59:00.000Z', applications: [], createdAt: '2026-03-02T08:00:00.000Z', updatedAt: '2026-03-02T08:00:00.000Z' },
  { id: 'job-9', title: 'Graphic Designer', company: 'Fiifi Studios', location: 'Accra, Ghana', jobType: 'CONTRACT', description: 'Fiifi Studios is looking for a freelance graphic designer for a 3-month branding project. Experience with brand identity design, packaging, and digital assets required.', contactEmail: 'hello@fiifistudios.com', externalUrl: 'https://fiifistudios.com/apply', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-03-25T23:59:00.000Z', applications: [], createdAt: '2026-03-06T08:00:00.000Z', updatedAt: '2026-03-06T08:00:00.000Z' },
  { id: 'job-10', title: 'Petroleum Engineer', company: 'Tullow Oil Ghana', location: 'Takoradi, Ghana', jobType: 'FULL_TIME', description: 'Tullow Oil is recruiting a petroleum engineer for our Western Region operations. You will support reservoir management, production optimisation, and well planning.', contactEmail: 'careers@tullowoil.com', externalUrl: 'https://tullowoil.com/careers', postedByName: 'Kwame Asante-Boateng', isApproved: false, expiresAt: '2026-05-30T23:59:00.000Z', applications: [], createdAt: '2026-03-12T08:00:00.000Z', updatedAt: '2026-03-12T08:00:00.000Z' },
  { id: 'job-11', title: 'Sales Representative', company: 'Fan Milk Ghana', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Fan Milk is looking for an energetic sales representative to manage key accounts in the Greater Accra region. Attractive base salary plus commission structure.', contactEmail: 'hr@fanmilk.com', externalUrl: 'https://fanmilk.com/careers', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-03-28T23:59:00.000Z', applications: [], createdAt: '2026-02-28T08:00:00.000Z', updatedAt: '2026-02-28T08:00:00.000Z' },
  { id: 'job-12', title: 'UI/UX Designer', company: 'mPharma', location: 'Accra, Ghana (Remote-friendly)', jobType: 'FULL_TIME', description: 'mPharma is looking for a UI/UX designer to improve the user experience of our healthcare technology platform serving patients across Africa.', contactEmail: 'design-careers@mpharma.com', externalUrl: 'https://mpharma.com/careers', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-04-18T23:59:00.000Z', applications: [], createdAt: '2026-03-03T08:00:00.000Z', updatedAt: '2026-03-03T08:00:00.000Z' },
  { id: 'job-13', title: 'Accountant', company: 'Ecobank Ghana', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Ecobank is hiring an accountant for the finance department. Responsibilities include financial reporting, reconciliation, and audit support.', contactEmail: 'careers@ecobank.com', externalUrl: 'https://ecobank.com/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-04-05T23:59:00.000Z', applications: [], createdAt: '2026-01-15T08:00:00.000Z', updatedAt: '2026-03-10T08:00:00.000Z' },
  { id: 'job-14', title: 'Content Writer', company: 'UPOSA Secretariat', location: 'Remote', jobType: 'PART_TIME', description: 'UPOSA is looking for a part-time content writer to create articles, social media posts, and newsletter content. This is a paid role for alumni with writing experience.', contactEmail: 'secretariat@uposa.org', externalUrl: 'https://uposa.org/careers/content-writer', postedByName: 'Abena Mensah-Kusi', isApproved: true, expiresAt: '2026-04-01T23:59:00.000Z', applications: [], createdAt: '2026-03-07T08:00:00.000Z', updatedAt: '2026-03-07T08:00:00.000Z' },
  { id: 'job-15', title: 'Dentist', company: 'Adjei Dental Clinic', location: 'Kumasi, Ghana', jobType: 'FULL_TIME', description: 'Adjei Dental Clinic is expanding and seeking a qualified dentist. Modern facilities, competitive pay, and professional growth opportunities.', contactEmail: 'info@adjeidental.com', externalUrl: 'https://adjeidental.com/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-05-10T23:59:00.000Z', applications: [], createdAt: '2026-03-09T08:00:00.000Z', updatedAt: '2026-03-09T08:00:00.000Z' },
  { id: 'job-16', title: 'Supply Chain Coordinator', company: 'Frimpong Logistics Ltd', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Frimpong Logistics is hiring a supply chain coordinator to manage warehousing, inventory, and distribution across our Accra operations centre.', contactEmail: 'careers@frimponglogistics.com', externalUrl: 'https://frimponglogistics.com/careers', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-04-22T23:59:00.000Z', applications: [], createdAt: '2026-03-11T08:00:00.000Z', updatedAt: '2026-03-11T08:00:00.000Z' },
  { id: 'job-17', title: 'Hotel Front Desk Manager', company: 'Golden Tulip Kumasi', location: 'Kumasi, Ghana', jobType: 'FULL_TIME', description: 'Golden Tulip Kumasi seeks an experienced front desk manager to lead our guest services team. You will ensure exceptional guest experiences and manage front office operations.', contactEmail: 'hr@goldentulipkumasi.com', externalUrl: 'https://goldentulipkumasi.com/careers', postedByName: 'Abena Mensah-Kusi', isApproved: true, expiresAt: '2026-04-08T23:59:00.000Z', applications: [], createdAt: '2026-02-18T08:00:00.000Z', updatedAt: '2026-02-18T08:00:00.000Z' },
  { id: 'job-18', title: 'Research Assistant', company: 'KNUST', location: 'Kumasi, Ghana', jobType: 'CONTRACT', description: 'KNUST Department of Biochemistry is looking for a research assistant for a 12-month malaria vaccine research project. Funded by the Wellcome Trust.', contactEmail: 'research@knust.edu.gh', externalUrl: 'https://knust.edu.gh/research-jobs', postedByName: 'Abena Mensah-Kusi', isApproved: false, expiresAt: '2026-03-30T23:59:00.000Z', applications: [], createdAt: '2026-03-13T08:00:00.000Z', updatedAt: '2026-03-13T08:00:00.000Z' },
  { id: 'job-19', title: 'Branch Manager', company: 'Fidelity Bank Ghana', location: 'Takoradi, Ghana', jobType: 'FULL_TIME', description: 'Fidelity Bank seeks an experienced branch manager for our Takoradi main branch. Lead a team of 15+ and drive business growth in the Western Region.', contactEmail: 'careers@fidelitybank.com.gh', externalUrl: 'https://fidelitybank.com.gh/careers', postedByName: 'Kwame Asante-Boateng', isApproved: true, expiresAt: '2026-05-05T23:59:00.000Z', applications: [], createdAt: '2026-03-04T08:00:00.000Z', updatedAt: '2026-03-04T08:00:00.000Z' },
  { id: 'job-20', title: 'Architect', company: 'Amankwah Design Studio', location: 'Accra, Ghana', jobType: 'FULL_TIME', description: 'Amankwah Design Studio is looking for a creative architect to join our residential and commercial projects team. We specialise in sustainable, modern African architecture.', contactEmail: 'careers@amankwahdesign.com', externalUrl: 'https://amankwahdesign.com/careers', postedByName: 'Ama Osei-Bonsu', isApproved: true, expiresAt: '2026-04-28T23:59:00.000Z', applications: [], createdAt: '2026-03-14T08:00:00.000Z', updatedAt: '2026-03-14T08:00:00.000Z' },
]

interface JobsState {
  jobs: Job[]
  addJob: (job: Omit<Job, 'id' | 'createdAt' | 'updatedAt'>) => Job
  updateJob: (id: string, updates: Partial<Job>) => void
  deleteJob: (id: string) => void
  resetToDefaults: () => void
}

export const useJobsStore = create<JobsState>()(
  persist(
    (set) => ({
      jobs: MOCK_JOBS,
      addJob: (job) => {
        const newJob: Job = {
          ...job,
          id: `job-${Date.now()}`,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        }
        set((s) => ({ jobs: [newJob, ...s.jobs] }))
        return newJob
      },
      updateJob: (id, updates) =>
        set((s) => ({
          jobs: s.jobs.map((j) =>
            j.id === id ? { ...j, ...updates, updatedAt: new Date().toISOString() } : j
          ),
        })),
      deleteJob: (id) =>
        set((s) => ({ jobs: s.jobs.filter((j) => j.id !== id) })),
      resetToDefaults: () => set({ jobs: MOCK_JOBS }),
    }),
    { name: 'uposa_jobs', version: 2 }
  )
)
