import type { Permission, Role } from '../types'

export const ROLES: Record<Role, string> = {
  super_admin: 'Super Admin',
  content_manager: 'Content Manager',
  membership_manager: 'Membership Manager',
  moderator: 'Moderator',
}

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  super_admin: [
    'alumni:view', 'alumni:approve', 'alumni:reject', 'alumni:export',
    'members:view',
    'events:view', 'events:create', 'events:edit', 'events:delete',
    'news:view', 'news:create', 'news:edit', 'news:delete',
    'projects:view', 'projects:create', 'projects:edit', 'projects:delete',
    'donations:view', 'donations:create', 'donations:edit', 'donations:delete', 'donations:export',
    'admin_users:view', 'admin_users:create', 'admin_users:edit', 'admin_users:delete', 'admin_users:assign_role',
    'roles:view', 'roles:edit',
    'settings:view', 'settings:edit',
    'content:view', 'content:create', 'content:edit', 'content:delete',
    'executives:view', 'executives:create', 'executives:edit', 'executives:delete',
    'jobs:view', 'jobs:create', 'jobs:edit', 'jobs:delete',
    'elections:view', 'elections:create', 'elections:edit', 'elections:delete',
    'polls:view', 'polls:create', 'polls:edit', 'polls:delete',
    'forum:view', 'forum:moderate',
    'announcements:view', 'announcements:create', 'announcements:edit', 'announcements:delete',
    'contact:view', 'contact:manage',
  ],
  content_manager: [
    'events:view', 'events:create', 'events:edit', 'events:delete',
    'news:view', 'news:create', 'news:edit', 'news:delete',
    'projects:view', 'projects:create', 'projects:edit', 'projects:delete',
    'donations:view', 'donations:create', 'donations:edit', 'donations:export',
    'settings:view',
    'content:view', 'content:create', 'content:edit', 'content:delete',
    'executives:view', 'executives:create', 'executives:edit',
    'jobs:view', 'jobs:create', 'jobs:edit', 'jobs:delete',
    'polls:view', 'polls:create', 'polls:edit', 'polls:delete',
    'forum:view',
    'announcements:view', 'announcements:create', 'announcements:edit', 'announcements:delete',
  ],
  membership_manager: [
    'alumni:view', 'alumni:approve', 'alumni:reject', 'alumni:export',
    'members:view',
    'executives:view',
    'jobs:view',
    'elections:view', 'elections:create',
    'polls:view',
    'forum:view', 'forum:moderate',
    'contact:view', 'contact:manage',
  ],
  moderator: [
    'alumni:view',
    'members:view',
    'events:view',
    'news:view',
    'projects:view',
    'content:view',
    'executives:view',
    'jobs:view',
    'elections:view',
    'polls:view',
    'forum:view',
    'announcements:view',
    'contact:view',
  ],
}
